image:
  file: .gitpod.Dockerfile

ports:
  - port: 5005
    visibility: private
    onOpen: ignore
  
  - port: 5555
    visibility: private
    onOpen: ignore

  - port: 3006
    visibility: private
    onOpen: ignore

  - port: 8080
    visibility: public
    onOpen: ignore
    
  - port: 8888
    visibility: public
    onOpen: ignore
